import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import AddRentInfoModal from "@/components/modals/AddRentInfoModal";
import UpdateRentInfoModal from "@/components/modals/UpdateRentInfo";
import DialogBox from "@/components/DialogBox";
import { getUserId } from "./lib/action";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  const userId = await getUserId();
  return (
    <html lang="en">
      <body>

        <NavBar userId = {userId}/>

        {children}
        <AddRentInfoModal/>
        <UpdateRentInfoModal/>
        <Toaster/>
        <div id="scroll" className=" ">
           <DialogBox/>
        </div>
         <Footer/>

      </body>
    </html>
  );
}
